name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Publish
      shell: bash
      run: |
        dotnet publish --configuration Release --output build -p:GHPages=true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/wwwroot
        user_name: "Tolik Pylypchuk"
        user_email: "pylypchuk.tolik@gmail.com"
        commit_message: "Deploy to GitHub Pages"
        force_orphan: true
        cname: "darkness.tolik.io"
