name: GitHub Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build/wwwroot
        COMMIT_MESSAGE: "Deploy to GitHub Pages"
        SINGLE_COMMIT: true
